=== danimp3/LenguajedeMARCAS22-23/TEMA 1 INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/xsd/marcadores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="marcadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pagina" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="descripccion" type="xs:string"></xs:element>
                            <xs:element name="url" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>  
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== danimp3/LenguajedeMARCAS22-23/TEMA 1 INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/xsd/marcadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="marcadores.xsd">

    <pagina>
            <nombre>vbb</nombre>
            <descripccion>asdca</descripccion>
            <url>adada</url>
    </pagina>
    <pagina>
            <nombre>asdasdas</nombre>
            <descripccion>asdasdasd</descripccion>
            <url>dasdassdasd</url>
    </pagina>
    <pagina>
        <nombre>daadasd</nombre>
        <descripccion>asdfsdf</descripccion>
        <url>fdsfwef</url>
    </pagina>
</marcadores>
