=== danimp3/LenguajedeMARCAS22-23/TEMA 1 INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/xsd/cuadernillo/ej5/fichas2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fichas2">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="iniciales" type="xs:tiniciales"/>
                             <xs:element name="edad" type="xs:integer" />
                            <xs:element name="iniciales-al-reves" type="xs:tiniciales"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tiniciales">
          <xs:restriction base="xs:string">
              <xs:pattern value="[A-Z][A-Z][A-Z]" />
          </xs:restriction>
                            </xs:simpleType>
</xs:schema>

=== danimp3/LenguajedeMARCAS22-23/TEMA 1 INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/xsd/cuadernillo/ej5/fichas2.xml
<?xml version="1.0" encoding="UTF-8"?>
<fichas2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="fichas2.xsd">
    <ficha>
        <nombre>Ana Sanz Tin</nombre>
        <iniciales>AST</iniciales>
        <edad>22</edad>
        <iniciales-al-reves>TSA</iniciales-al-reves>
    </ficha>
    <ficha>
        <nombre>Iker Rubio Mol</nombre>
        <iniciales>IRM</iniciales>
        <edad>23</edad>
        <iniciales-al-reves>MRI</iniciales-al-reves>
    </ficha>
</fichas2>
